"""init

Revision ID: dcb84fe74273
Revises: 
Create Date: 2026-08-14 11:52:30.322873

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dcb84fe74273'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_snapshot',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=40), nullable=False),
    sa.Column('prompt_snapshot', sa.Text(), nullable=True),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_trace_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id')
    )
    op.create_table('human_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('human_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('human_id')
    )
    op.create_table('project',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('agent',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('owner_human_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_human_id'], ['human_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_table('human_project_scope',
    sa.Column('human_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['human_user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('human_id', 'project_id')
    )
    op.create_table('agent_project_scope',
    sa.Column('agent_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'project_id')
    )
    op.create_table('artifact',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('artifact_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('artifact_type', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('creator_agent_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_human_id', sa.BigInteger(), nullable=False),
    sa.Column('current_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('content_storage', sa.Text(), server_default='inline', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['owner_human_id'], ['human_user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id')
    )
    op.create_index('ix_artifact_created_at', 'artifact', ['created_at'], unique=False)
    op.create_index('ix_artifact_creator_agent_id', 'artifact', ['creator_agent_id'], unique=False)
    op.create_index('ix_artifact_project_id', 'artifact', ['project_id'], unique=False)
    op.create_index('ix_artifact_tags', 'artifact', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_artifact_type', 'artifact', ['artifact_type'], unique=False)
    op.create_table('artifact_lineage',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('child_artifact_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_artifact_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_version_no', sa.Integer(), nullable=True),
    sa.Column('forked_by_agent_id', sa.BigInteger(), nullable=True),
    sa.Column('fork_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_artifact_id'], ['artifact.id'], ),
    sa.ForeignKeyConstraint(['forked_by_agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['artifact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifact_lineage_child', 'artifact_lineage', ['child_artifact_id'], unique=True)
    op.create_table('artifact_version',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('artifact_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_format', sa.Text(), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('created_by_agent_id', sa.BigInteger(), nullable=True),
    sa.Column('context_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], ),
    sa.ForeignKeyConstraint(['context_snapshot_id'], ['context_snapshot.id'], ),
    sa.ForeignKeyConstraint(['created_by_agent_id'], ['agent.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifact_version_artifact_version', 'artifact_version', ['artifact_id', 'version_no'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('actor_agent_id', sa.BigInteger(), nullable=True),
    sa.Column('on_behalf_of_human_id', sa.BigInteger(), nullable=True),
    sa.Column('actor_human_id', sa.BigInteger(), nullable=True),
    sa.Column('target_artifact_id', sa.BigInteger(), nullable=True),
    sa.Column('target_version_no', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['actor_human_id'], ['human_user.id'], ),
    sa.ForeignKeyConstraint(['on_behalf_of_human_id'], ['human_user.id'], ),
    sa.ForeignKeyConstraint(['target_artifact_id'], ['artifact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_actor_agent_id', 'audit_log', ['actor_agent_id'], unique=False)
    op.create_index('ix_audit_log_on_behalf_of_human_id', 'audit_log', ['on_behalf_of_human_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('artifact_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('author_human_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('inline_anchor', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifact.id'], ),
    sa.ForeignKeyConstraint(['author_human_id'], ['human_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_artifact_version', 'feedback', ['artifact_id', 'version_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_artifact_version', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_audit_log_on_behalf_of_human_id', table_name='audit_log')
    op.drop_index('ix_audit_log_actor_agent_id', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_artifact_version_artifact_version', table_name='artifact_version')
    op.drop_table('artifact_version')
    op.drop_index('ix_artifact_lineage_child', table_name='artifact_lineage')
    op.drop_table('artifact_lineage')
    op.drop_index('ix_artifact_type', table_name='artifact')
    op.drop_index('ix_artifact_tags', table_name='artifact', postgresql_using='gin')
    op.drop_index('ix_artifact_project_id', table_name='artifact')
    op.drop_index('ix_artifact_creator_agent_id', table_name='artifact')
    op.drop_index('ix_artifact_created_at', table_name='artifact')
    op.drop_table('artifact')
    op.drop_table('agent_project_scope')
    op.drop_table('human_project_scope')
    op.drop_table('agent')
    op.drop_table('project')
    op.drop_table('human_user')
    op.drop_table('context_snapshot')
    # ### end Alembic commands ###
